import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Analytics } from '@vercel/analytics/next';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Akshay Shinde - Resume',
  description: 'Generated by Akshay Shinde',
  keywords: [
    'Akshay Shinde Resume',
    `Akshay Shinde's Resume`,
    'Resume',
    'Resume Akshay Shinde',
    'Senior software engineer',
    'SDE-4',
    'SWE-4',
    'Problem Solver',
    'Akshay Shinde',
    'Front end engineer',
    'Full stack engineer',
    'Devops engineer',
    'Tech Lead',
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
